### ISSUE TITLE
Outline for Kiribati missing

### ISSUE THREAD

**Issue by pistell** [DevangPatel18/Map-Quiz#18]
<img width="1039" alt="Screen Shot 2019-09-02 at 1 10 54 PM" src="https://user-images.githubusercontent.com/7827805/64128199-54492380-cd83-11e9-85a0-47aab87dca05.png">

The ellipse outline for Kiribati is missing.

**Comment by DevangPatel18** [comment]
Should be there now

**Comment by DevangPatel18** [comment]
Pushed an update, now it's there.

**Comment by pistell** [comment]
Thanks Devang. I play this game every day :)
